//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.0.2+497c31e
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Global Settings</summary>
	[PublishedModel("globalSettings")]
	public partial class GlobalSettings : PublishedContentModel, IFooterSettings, IHeaderSettings, ISeoSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		public new const string ModelTypeAlias = "globalSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<GlobalSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public GlobalSettings(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Desktop: Fallback Header Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerSettingsLogoDesktop")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FooterSettingsLogoDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.FooterSettings.GetFooterSettingsLogoDesktop(this, _publishedValueFallback);

		///<summary>
		/// Mobile: Fallback Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerSettingsLogoMobile")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FooterSettingsLogoMobile => global::Umbraco.Cms.Web.Common.PublishedModels.FooterSettings.GetFooterSettingsLogoMobile(this, _publishedValueFallback);

		///<summary>
		/// Tablet: Fallback Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerSettingsLogoTablet")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FooterSettingsLogoTablet => global::Umbraco.Cms.Web.Common.PublishedModels.FooterSettings.GetFooterSettingsLogoTablet(this, _publishedValueFallback);

		///<summary>
		/// Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerSettingsLogoDesktop")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeaderSettingsLogoDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderSettings.GetHeaderSettingsLogoDesktop(this, _publishedValueFallback);

		///<summary>
		/// Mobile: Fallback Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerSettingsLogoMobile")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeaderSettingsLogoMobile => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderSettings.GetHeaderSettingsLogoMobile(this, _publishedValueFallback);

		///<summary>
		/// Tablet: Fallback Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerSettingsLogoTablet")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeaderSettingsLogoTablet => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderSettings.GetHeaderSettingsLogoTablet(this, _publishedValueFallback);

		///<summary>
		/// Global SEO Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("globalSeoDescription")]
		public virtual string GlobalSeoDescription => global::Umbraco.Cms.Web.Common.PublishedModels.SeoSettings.GetGlobalSeoDescription(this, _publishedValueFallback);

		///<summary>
		/// Global SEO Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("globalSeoTitle")]
		public virtual string GlobalSeoTitle => global::Umbraco.Cms.Web.Common.PublishedModels.SeoSettings.GetGlobalSeoTitle(this, _publishedValueFallback);

		///<summary>
		/// Global Title Prefix
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("globalSeoTitlePrefix")]
		public virtual string GlobalSeoTitlePrefix => global::Umbraco.Cms.Web.Common.PublishedModels.SeoSettings.GetGlobalSeoTitlePrefix(this, _publishedValueFallback);

		///<summary>
		/// Global Title Suffix
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("globalSeoTitleSuffix")]
		public virtual string GlobalSeoTitleSuffix => global::Umbraco.Cms.Web.Common.PublishedModels.SeoSettings.GetGlobalSeoTitleSuffix(this, _publishedValueFallback);
	}
}
