//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.0.0+da502e0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Settings</summary>
	[PublishedModel("settings")]
	public partial class Settings : PublishedContentModel, IFooterSettings, IHeaderSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.0+da502e0")]
		public new const string ModelTypeAlias = "settings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.0+da502e0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.0+da502e0")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.0+da502e0")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<Settings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Settings(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Desktop: Fallback Header Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.0+da502e0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerSettingsLogoDesktop")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FooterSettingsLogoDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.FooterSettings.GetFooterSettingsLogoDesktop(this, _publishedValueFallback);

		///<summary>
		/// Mobile: Fallback Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.0+da502e0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerSettingsLogoMobile")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FooterSettingsLogoMobile => global::Umbraco.Cms.Web.Common.PublishedModels.FooterSettings.GetFooterSettingsLogoMobile(this, _publishedValueFallback);

		///<summary>
		/// Tablet: Fallback Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.0+da502e0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerSettingsLogoTablet")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FooterSettingsLogoTablet => global::Umbraco.Cms.Web.Common.PublishedModels.FooterSettings.GetFooterSettingsLogoTablet(this, _publishedValueFallback);

		///<summary>
		/// Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.0+da502e0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerSettingsLogoDesktop")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeaderSettingsLogoDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderSettings.GetHeaderSettingsLogoDesktop(this, _publishedValueFallback);

		///<summary>
		/// Mobile: Fallback Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.0+da502e0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerSettingsLogoMobile")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeaderSettingsLogoMobile => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderSettings.GetHeaderSettingsLogoMobile(this, _publishedValueFallback);

		///<summary>
		/// Tablet: Fallback Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.0+da502e0")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerSettingsLogoTablet")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeaderSettingsLogoTablet => global::Umbraco.Cms.Web.Common.PublishedModels.HeaderSettings.GetHeaderSettingsLogoTablet(this, _publishedValueFallback);
	}
}
